// Code generated by go-swagger; DO NOT EDIT.

package api_key

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAPIKeyRemoveParams creates a new APIKeyRemoveParams object
// with the default values initialized.
func NewAPIKeyRemoveParams() *APIKeyRemoveParams {
	var ()
	return &APIKeyRemoveParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAPIKeyRemoveParamsWithTimeout creates a new APIKeyRemoveParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAPIKeyRemoveParamsWithTimeout(timeout time.Duration) *APIKeyRemoveParams {
	var ()
	return &APIKeyRemoveParams{

		timeout: timeout,
	}
}

// NewAPIKeyRemoveParamsWithContext creates a new APIKeyRemoveParams object
// with the default values initialized, and the ability to set a context for a request
func NewAPIKeyRemoveParamsWithContext(ctx context.Context) *APIKeyRemoveParams {
	var ()
	return &APIKeyRemoveParams{

		Context: ctx,
	}
}

// NewAPIKeyRemoveParamsWithHTTPClient creates a new APIKeyRemoveParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAPIKeyRemoveParamsWithHTTPClient(client *http.Client) *APIKeyRemoveParams {
	var ()
	return &APIKeyRemoveParams{
		HTTPClient: client,
	}
}

/*APIKeyRemoveParams contains all the parameters to send to the API endpoint
for the API key remove operation typically these are written to a http.Request
*/
type APIKeyRemoveParams struct {

	/*APIKeyID
	  API Key ID (public component).

	*/
	APIKeyID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the API key remove params
func (o *APIKeyRemoveParams) WithTimeout(timeout time.Duration) *APIKeyRemoveParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the API key remove params
func (o *APIKeyRemoveParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the API key remove params
func (o *APIKeyRemoveParams) WithContext(ctx context.Context) *APIKeyRemoveParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the API key remove params
func (o *APIKeyRemoveParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the API key remove params
func (o *APIKeyRemoveParams) WithHTTPClient(client *http.Client) *APIKeyRemoveParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the API key remove params
func (o *APIKeyRemoveParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIKeyID adds the aPIKeyID to the API key remove params
func (o *APIKeyRemoveParams) WithAPIKeyID(aPIKeyID string) *APIKeyRemoveParams {
	o.SetAPIKeyID(aPIKeyID)
	return o
}

// SetAPIKeyID adds the apiKeyId to the API key remove params
func (o *APIKeyRemoveParams) SetAPIKeyID(aPIKeyID string) {
	o.APIKeyID = aPIKeyID
}

// WriteToRequest writes these params to a swagger request
func (o *APIKeyRemoveParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// form param apiKeyID
	frAPIKeyID := o.APIKeyID
	fAPIKeyID := frAPIKeyID
	if fAPIKeyID != "" {
		if err := r.SetFormParam("apiKeyID", fAPIKeyID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
