// Code generated by go-swagger; DO NOT EDIT.

package position

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPositionTransferIsolatedMarginParams creates a new PositionTransferIsolatedMarginParams object
// with the default values initialized.
func NewPositionTransferIsolatedMarginParams() *PositionTransferIsolatedMarginParams {
	var ()
	return &PositionTransferIsolatedMarginParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPositionTransferIsolatedMarginParamsWithTimeout creates a new PositionTransferIsolatedMarginParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPositionTransferIsolatedMarginParamsWithTimeout(timeout time.Duration) *PositionTransferIsolatedMarginParams {
	var ()
	return &PositionTransferIsolatedMarginParams{

		timeout: timeout,
	}
}

// NewPositionTransferIsolatedMarginParamsWithContext creates a new PositionTransferIsolatedMarginParams object
// with the default values initialized, and the ability to set a context for a request
func NewPositionTransferIsolatedMarginParamsWithContext(ctx context.Context) *PositionTransferIsolatedMarginParams {
	var ()
	return &PositionTransferIsolatedMarginParams{

		Context: ctx,
	}
}

// NewPositionTransferIsolatedMarginParamsWithHTTPClient creates a new PositionTransferIsolatedMarginParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPositionTransferIsolatedMarginParamsWithHTTPClient(client *http.Client) *PositionTransferIsolatedMarginParams {
	var ()
	return &PositionTransferIsolatedMarginParams{
		HTTPClient: client,
	}
}

/*PositionTransferIsolatedMarginParams contains all the parameters to send to the API endpoint
for the position transfer isolated margin operation typically these are written to a http.Request
*/
type PositionTransferIsolatedMarginParams struct {

	/*Amount
	  Amount to transfer, in Satoshis. May be negative.

	*/
	Amount int64
	/*Symbol
	  Symbol of position to isolate.

	*/
	Symbol string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the position transfer isolated margin params
func (o *PositionTransferIsolatedMarginParams) WithTimeout(timeout time.Duration) *PositionTransferIsolatedMarginParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the position transfer isolated margin params
func (o *PositionTransferIsolatedMarginParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the position transfer isolated margin params
func (o *PositionTransferIsolatedMarginParams) WithContext(ctx context.Context) *PositionTransferIsolatedMarginParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the position transfer isolated margin params
func (o *PositionTransferIsolatedMarginParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the position transfer isolated margin params
func (o *PositionTransferIsolatedMarginParams) WithHTTPClient(client *http.Client) *PositionTransferIsolatedMarginParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the position transfer isolated margin params
func (o *PositionTransferIsolatedMarginParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAmount adds the amount to the position transfer isolated margin params
func (o *PositionTransferIsolatedMarginParams) WithAmount(amount int64) *PositionTransferIsolatedMarginParams {
	o.SetAmount(amount)
	return o
}

// SetAmount adds the amount to the position transfer isolated margin params
func (o *PositionTransferIsolatedMarginParams) SetAmount(amount int64) {
	o.Amount = amount
}

// WithSymbol adds the symbol to the position transfer isolated margin params
func (o *PositionTransferIsolatedMarginParams) WithSymbol(symbol string) *PositionTransferIsolatedMarginParams {
	o.SetSymbol(symbol)
	return o
}

// SetSymbol adds the symbol to the position transfer isolated margin params
func (o *PositionTransferIsolatedMarginParams) SetSymbol(symbol string) {
	o.Symbol = symbol
}

// WriteToRequest writes these params to a swagger request
func (o *PositionTransferIsolatedMarginParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// form param amount
	frAmount := o.Amount
	fAmount := swag.FormatInt64(frAmount)
	if fAmount != "" {
		if err := r.SetFormParam("amount", fAmount); err != nil {
			return err
		}
	}

	// form param symbol
	frSymbol := o.Symbol
	fSymbol := frSymbol
	if fSymbol != "" {
		if err := r.SetFormParam("symbol", fSymbol); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
