// Code generated by go-swagger; DO NOT EDIT.

package instrument

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewInstrumentGetActiveParams creates a new InstrumentGetActiveParams object
// with the default values initialized.
func NewInstrumentGetActiveParams() *InstrumentGetActiveParams {

	return &InstrumentGetActiveParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewInstrumentGetActiveParamsWithTimeout creates a new InstrumentGetActiveParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewInstrumentGetActiveParamsWithTimeout(timeout time.Duration) *InstrumentGetActiveParams {

	return &InstrumentGetActiveParams{

		timeout: timeout,
	}
}

// NewInstrumentGetActiveParamsWithContext creates a new InstrumentGetActiveParams object
// with the default values initialized, and the ability to set a context for a request
func NewInstrumentGetActiveParamsWithContext(ctx context.Context) *InstrumentGetActiveParams {

	return &InstrumentGetActiveParams{

		Context: ctx,
	}
}

// NewInstrumentGetActiveParamsWithHTTPClient creates a new InstrumentGetActiveParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewInstrumentGetActiveParamsWithHTTPClient(client *http.Client) *InstrumentGetActiveParams {

	return &InstrumentGetActiveParams{
		HTTPClient: client,
	}
}

/*InstrumentGetActiveParams contains all the parameters to send to the API endpoint
for the instrument get active operation typically these are written to a http.Request
*/
type InstrumentGetActiveParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the instrument get active params
func (o *InstrumentGetActiveParams) WithTimeout(timeout time.Duration) *InstrumentGetActiveParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the instrument get active params
func (o *InstrumentGetActiveParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the instrument get active params
func (o *InstrumentGetActiveParams) WithContext(ctx context.Context) *InstrumentGetActiveParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the instrument get active params
func (o *InstrumentGetActiveParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the instrument get active params
func (o *InstrumentGetActiveParams) WithHTTPClient(client *http.Client) *InstrumentGetActiveParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the instrument get active params
func (o *InstrumentGetActiveParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *InstrumentGetActiveParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
