// Code generated by go-swagger; DO NOT EDIT.

package instrument

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewInstrumentGetIndicesParams creates a new InstrumentGetIndicesParams object
// with the default values initialized.
func NewInstrumentGetIndicesParams() *InstrumentGetIndicesParams {

	return &InstrumentGetIndicesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewInstrumentGetIndicesParamsWithTimeout creates a new InstrumentGetIndicesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewInstrumentGetIndicesParamsWithTimeout(timeout time.Duration) *InstrumentGetIndicesParams {

	return &InstrumentGetIndicesParams{

		timeout: timeout,
	}
}

// NewInstrumentGetIndicesParamsWithContext creates a new InstrumentGetIndicesParams object
// with the default values initialized, and the ability to set a context for a request
func NewInstrumentGetIndicesParamsWithContext(ctx context.Context) *InstrumentGetIndicesParams {

	return &InstrumentGetIndicesParams{

		Context: ctx,
	}
}

// NewInstrumentGetIndicesParamsWithHTTPClient creates a new InstrumentGetIndicesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewInstrumentGetIndicesParamsWithHTTPClient(client *http.Client) *InstrumentGetIndicesParams {

	return &InstrumentGetIndicesParams{
		HTTPClient: client,
	}
}

/*InstrumentGetIndicesParams contains all the parameters to send to the API endpoint
for the instrument get indices operation typically these are written to a http.Request
*/
type InstrumentGetIndicesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the instrument get indices params
func (o *InstrumentGetIndicesParams) WithTimeout(timeout time.Duration) *InstrumentGetIndicesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the instrument get indices params
func (o *InstrumentGetIndicesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the instrument get indices params
func (o *InstrumentGetIndicesParams) WithContext(ctx context.Context) *InstrumentGetIndicesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the instrument get indices params
func (o *InstrumentGetIndicesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the instrument get indices params
func (o *InstrumentGetIndicesParams) WithHTTPClient(client *http.Client) *InstrumentGetIndicesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the instrument get indices params
func (o *InstrumentGetIndicesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *InstrumentGetIndicesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
