// Code generated by go-swagger; DO NOT EDIT.

package chat

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewChatGetChannelsParams creates a new ChatGetChannelsParams object
// with the default values initialized.
func NewChatGetChannelsParams() *ChatGetChannelsParams {

	return &ChatGetChannelsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewChatGetChannelsParamsWithTimeout creates a new ChatGetChannelsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewChatGetChannelsParamsWithTimeout(timeout time.Duration) *ChatGetChannelsParams {

	return &ChatGetChannelsParams{

		timeout: timeout,
	}
}

// NewChatGetChannelsParamsWithContext creates a new ChatGetChannelsParams object
// with the default values initialized, and the ability to set a context for a request
func NewChatGetChannelsParamsWithContext(ctx context.Context) *ChatGetChannelsParams {

	return &ChatGetChannelsParams{

		Context: ctx,
	}
}

// NewChatGetChannelsParamsWithHTTPClient creates a new ChatGetChannelsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewChatGetChannelsParamsWithHTTPClient(client *http.Client) *ChatGetChannelsParams {

	return &ChatGetChannelsParams{
		HTTPClient: client,
	}
}

/*ChatGetChannelsParams contains all the parameters to send to the API endpoint
for the chat get channels operation typically these are written to a http.Request
*/
type ChatGetChannelsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the chat get channels params
func (o *ChatGetChannelsParams) WithTimeout(timeout time.Duration) *ChatGetChannelsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the chat get channels params
func (o *ChatGetChannelsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the chat get channels params
func (o *ChatGetChannelsParams) WithContext(ctx context.Context) *ChatGetChannelsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the chat get channels params
func (o *ChatGetChannelsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the chat get channels params
func (o *ChatGetChannelsParams) WithHTTPClient(client *http.Client) *ChatGetChannelsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the chat get channels params
func (o *ChatGetChannelsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ChatGetChannelsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
