// Code generated by go-swagger; DO NOT EDIT.

package stats

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewStatsHistoryParams creates a new StatsHistoryParams object
// with the default values initialized.
func NewStatsHistoryParams() *StatsHistoryParams {

	return &StatsHistoryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewStatsHistoryParamsWithTimeout creates a new StatsHistoryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewStatsHistoryParamsWithTimeout(timeout time.Duration) *StatsHistoryParams {

	return &StatsHistoryParams{

		timeout: timeout,
	}
}

// NewStatsHistoryParamsWithContext creates a new StatsHistoryParams object
// with the default values initialized, and the ability to set a context for a request
func NewStatsHistoryParamsWithContext(ctx context.Context) *StatsHistoryParams {

	return &StatsHistoryParams{

		Context: ctx,
	}
}

// NewStatsHistoryParamsWithHTTPClient creates a new StatsHistoryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewStatsHistoryParamsWithHTTPClient(client *http.Client) *StatsHistoryParams {

	return &StatsHistoryParams{
		HTTPClient: client,
	}
}

/*StatsHistoryParams contains all the parameters to send to the API endpoint
for the stats history operation typically these are written to a http.Request
*/
type StatsHistoryParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the stats history params
func (o *StatsHistoryParams) WithTimeout(timeout time.Duration) *StatsHistoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the stats history params
func (o *StatsHistoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the stats history params
func (o *StatsHistoryParams) WithContext(ctx context.Context) *StatsHistoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the stats history params
func (o *StatsHistoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the stats history params
func (o *StatsHistoryParams) WithHTTPClient(client *http.Client) *StatsHistoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the stats history params
func (o *StatsHistoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *StatsHistoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
