// Code generated by go-swagger; DO NOT EDIT.

package stats

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new stats API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for stats API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
StatsGet gets exchange wide and per series turnover and volume statistics
*/
func (a *Client) StatsGet(params *StatsGetParams) (*StatsGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewStatsGetParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "Stats.get",
		Method:             "GET",
		PathPattern:        "/stats",
		ProducesMediaTypes: []string{"application/javascript", "application/json", "application/xml", "text/javascript", "text/xml"},
		ConsumesMediaTypes: []string{"application/json", "application/x-www-form-urlencoded"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &StatsGetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*StatsGetOK), nil

}

/*
StatsHistory gets historical exchange wide and per series turnover and volume statistics
*/
func (a *Client) StatsHistory(params *StatsHistoryParams) (*StatsHistoryOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewStatsHistoryParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "Stats.history",
		Method:             "GET",
		PathPattern:        "/stats/history",
		ProducesMediaTypes: []string{"application/javascript", "application/json", "application/xml", "text/javascript", "text/xml"},
		ConsumesMediaTypes: []string{"application/json", "application/x-www-form-urlencoded"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &StatsHistoryReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*StatsHistoryOK), nil

}

/*
StatsHistoryUSD gets a summary of exchange statistics in u s d
*/
func (a *Client) StatsHistoryUSD(params *StatsHistoryUSDParams) (*StatsHistoryUSDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewStatsHistoryUSDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "Stats.historyUSD",
		Method:             "GET",
		PathPattern:        "/stats/historyUSD",
		ProducesMediaTypes: []string{"application/javascript", "application/json", "application/xml", "text/javascript", "text/xml"},
		ConsumesMediaTypes: []string{"application/json", "application/x-www-form-urlencoded"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &StatsHistoryUSDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*StatsHistoryUSDOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
