// Code generated by go-swagger; DO NOT EDIT.

package stats

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewStatsGetParams creates a new StatsGetParams object
// with the default values initialized.
func NewStatsGetParams() *StatsGetParams {

	return &StatsGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewStatsGetParamsWithTimeout creates a new StatsGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewStatsGetParamsWithTimeout(timeout time.Duration) *StatsGetParams {

	return &StatsGetParams{

		timeout: timeout,
	}
}

// NewStatsGetParamsWithContext creates a new StatsGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewStatsGetParamsWithContext(ctx context.Context) *StatsGetParams {

	return &StatsGetParams{

		Context: ctx,
	}
}

// NewStatsGetParamsWithHTTPClient creates a new StatsGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewStatsGetParamsWithHTTPClient(client *http.Client) *StatsGetParams {

	return &StatsGetParams{
		HTTPClient: client,
	}
}

/*StatsGetParams contains all the parameters to send to the API endpoint
for the stats get operation typically these are written to a http.Request
*/
type StatsGetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the stats get params
func (o *StatsGetParams) WithTimeout(timeout time.Duration) *StatsGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the stats get params
func (o *StatsGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the stats get params
func (o *StatsGetParams) WithContext(ctx context.Context) *StatsGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the stats get params
func (o *StatsGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the stats get params
func (o *StatsGetParams) WithHTTPClient(client *http.Client) *StatsGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the stats get params
func (o *StatsGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *StatsGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
