// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// UserLogoutReader is a Reader for the UserLogout structure.
type UserLogoutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UserLogoutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUserLogoutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUserLogoutOK creates a UserLogoutOK with default headers values
func NewUserLogoutOK() *UserLogoutOK {
	return &UserLogoutOK{}
}

/*UserLogoutOK handles this case with default header values.

Request was successful
*/
type UserLogoutOK struct {
	Payload interface{}
}

func (o *UserLogoutOK) Error() string {
	return fmt.Sprintf("[POST /user/logout][%d] userLogoutOK  %+v", 200, o.Payload)
}

func (o *UserLogoutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
