// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUserGetWalletHistoryParams creates a new UserGetWalletHistoryParams object
// with the default values initialized.
func NewUserGetWalletHistoryParams() *UserGetWalletHistoryParams {
	var (
		currencyDefault = string("XBt")
	)
	return &UserGetWalletHistoryParams{
		Currency: &currencyDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewUserGetWalletHistoryParamsWithTimeout creates a new UserGetWalletHistoryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUserGetWalletHistoryParamsWithTimeout(timeout time.Duration) *UserGetWalletHistoryParams {
	var (
		currencyDefault = string("XBt")
	)
	return &UserGetWalletHistoryParams{
		Currency: &currencyDefault,

		timeout: timeout,
	}
}

// NewUserGetWalletHistoryParamsWithContext creates a new UserGetWalletHistoryParams object
// with the default values initialized, and the ability to set a context for a request
func NewUserGetWalletHistoryParamsWithContext(ctx context.Context) *UserGetWalletHistoryParams {
	var (
		currencyDefault = string("XBt")
	)
	return &UserGetWalletHistoryParams{
		Currency: &currencyDefault,

		Context: ctx,
	}
}

// NewUserGetWalletHistoryParamsWithHTTPClient creates a new UserGetWalletHistoryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUserGetWalletHistoryParamsWithHTTPClient(client *http.Client) *UserGetWalletHistoryParams {
	var (
		currencyDefault = string("XBt")
	)
	return &UserGetWalletHistoryParams{
		Currency:   &currencyDefault,
		HTTPClient: client,
	}
}

/*UserGetWalletHistoryParams contains all the parameters to send to the API endpoint
for the user get wallet history operation typically these are written to a http.Request
*/
type UserGetWalletHistoryParams struct {

	/*Currency*/
	Currency *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the user get wallet history params
func (o *UserGetWalletHistoryParams) WithTimeout(timeout time.Duration) *UserGetWalletHistoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the user get wallet history params
func (o *UserGetWalletHistoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the user get wallet history params
func (o *UserGetWalletHistoryParams) WithContext(ctx context.Context) *UserGetWalletHistoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the user get wallet history params
func (o *UserGetWalletHistoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the user get wallet history params
func (o *UserGetWalletHistoryParams) WithHTTPClient(client *http.Client) *UserGetWalletHistoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the user get wallet history params
func (o *UserGetWalletHistoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCurrency adds the currency to the user get wallet history params
func (o *UserGetWalletHistoryParams) WithCurrency(currency *string) *UserGetWalletHistoryParams {
	o.SetCurrency(currency)
	return o
}

// SetCurrency adds the currency to the user get wallet history params
func (o *UserGetWalletHistoryParams) SetCurrency(currency *string) {
	o.Currency = currency
}

// WriteToRequest writes these params to a swagger request
func (o *UserGetWalletHistoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Currency != nil {

		// query param currency
		var qrCurrency string
		if o.Currency != nil {
			qrCurrency = *o.Currency
		}
		qCurrency := qrCurrency
		if qCurrency != "" {
			if err := r.SetQueryParam("currency", qCurrency); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
