// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/nntaoli-project/GoEx/bitmex/models"
)

// UserGetMarginReader is a Reader for the UserGetMargin structure.
type UserGetMarginReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UserGetMarginReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUserGetMarginOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUserGetMarginOK creates a UserGetMarginOK with default headers values
func NewUserGetMarginOK() *UserGetMarginOK {
	return &UserGetMarginOK{}
}

/*UserGetMarginOK handles this case with default header values.

Request was successful
*/
type UserGetMarginOK struct {
	Payload *models.Margin
}

func (o *UserGetMarginOK) Error() string {
	return fmt.Sprintf("[GET /user/margin][%d] userGetMarginOK  %+v", 200, *o.Payload)
}

func (o *UserGetMarginOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Margin)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
