// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// UserMinWithdrawalFeeReader is a Reader for the UserMinWithdrawalFee structure.
type UserMinWithdrawalFeeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UserMinWithdrawalFeeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUserMinWithdrawalFeeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUserMinWithdrawalFeeOK creates a UserMinWithdrawalFeeOK with default headers values
func NewUserMinWithdrawalFeeOK() *UserMinWithdrawalFeeOK {
	return &UserMinWithdrawalFeeOK{}
}

/*UserMinWithdrawalFeeOK handles this case with default header values.

Request was successful
*/
type UserMinWithdrawalFeeOK struct {
	Payload interface{}
}

func (o *UserMinWithdrawalFeeOK) Error() string {
	return fmt.Sprintf("[GET /user/minWithdrawalFee][%d] userMinWithdrawalFeeOK  %+v", 200, o.Payload)
}

func (o *UserMinWithdrawalFeeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
