// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/sumorf/bitmexwrap/bitmex/models"
)

// UserGetAffiliateStatusReader is a Reader for the UserGetAffiliateStatus structure.
type UserGetAffiliateStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UserGetAffiliateStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUserGetAffiliateStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUserGetAffiliateStatusOK creates a UserGetAffiliateStatusOK with default headers values
func NewUserGetAffiliateStatusOK() *UserGetAffiliateStatusOK {
	return &UserGetAffiliateStatusOK{}
}

/*UserGetAffiliateStatusOK handles this case with default header values.

Request was successful
*/
type UserGetAffiliateStatusOK struct {
	Payload *models.Affiliate
}

func (o *UserGetAffiliateStatusOK) Error() string {
	return fmt.Sprintf("[GET /user/affiliateStatus][%d] userGetAffiliateStatusOK  %+v", 200, *o.Payload)
}

func (o *UserGetAffiliateStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Affiliate)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
