// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// UserCheckReferralCodeReader is a Reader for the UserCheckReferralCode structure.
type UserCheckReferralCodeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UserCheckReferralCodeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUserCheckReferralCodeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUserCheckReferralCodeOK creates a UserCheckReferralCodeOK with default headers values
func NewUserCheckReferralCodeOK() *UserCheckReferralCodeOK {
	return &UserCheckReferralCodeOK{}
}

/*UserCheckReferralCodeOK handles this case with default header values.

Request was successful
*/
type UserCheckReferralCodeOK struct {
	Payload float64
}

func (o *UserCheckReferralCodeOK) Error() string {
	return fmt.Sprintf("[GET /user/checkReferralCode][%d] userCheckReferralCodeOK  %+v", 200, o.Payload)
}

func (o *UserCheckReferralCodeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
