// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// UserGetDepositAddressReader is a Reader for the UserGetDepositAddress structure.
type UserGetDepositAddressReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UserGetDepositAddressReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUserGetDepositAddressOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUserGetDepositAddressOK creates a UserGetDepositAddressOK with default headers values
func NewUserGetDepositAddressOK() *UserGetDepositAddressOK {
	return &UserGetDepositAddressOK{}
}

/*UserGetDepositAddressOK handles this case with default header values.

Request was successful
*/
type UserGetDepositAddressOK struct {
	Payload string
}

func (o *UserGetDepositAddressOK) Error() string {
	return fmt.Sprintf("[GET /user/depositAddress][%d] userGetDepositAddressOK  %+v", 200, o.Payload)
}

func (o *UserGetDepositAddressOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
