// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// UserLogoutAllReader is a Reader for the UserLogoutAll structure.
type UserLogoutAllReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UserLogoutAllReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUserLogoutAllOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUserLogoutAllOK creates a UserLogoutAllOK with default headers values
func NewUserLogoutAllOK() *UserLogoutAllOK {
	return &UserLogoutAllOK{}
}

/*UserLogoutAllOK handles this case with default header values.

Request was successful
*/
type UserLogoutAllOK struct {
	Payload float64
}

func (o *UserLogoutAllOK) Error() string {
	return fmt.Sprintf("[POST /user/logoutAll][%d] userLogoutAllOK  %+v", 200, o.Payload)
}

func (o *UserLogoutAllOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
