// Code generated by go-swagger; DO NOT EDIT.

package order_book

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new order book API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for order book API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
OrderBookGetL2 gets current orderbook in vertical format
*/
func (a *Client) OrderBookGetL2(params *OrderBookGetL2Params) (*OrderBookGetL2OK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewOrderBookGetL2Params()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "OrderBook.getL2",
		Method:             "GET",
		PathPattern:        "/orderBook/L2",
		ProducesMediaTypes: []string{"application/javascript", "application/json", "application/xml", "text/javascript", "text/xml"},
		ConsumesMediaTypes: []string{"application/json", "application/x-www-form-urlencoded"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &OrderBookGetL2Reader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*OrderBookGetL2OK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
